apiVersion: v1
kind: Service

metadata:
  name: secure-cloud-service

spec:
  type: LoadBalancer

  selector:
    app: secure-cloud-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
